Name:           perl-PDL-Slatec
Version:        2.097
Release:        2%{?dist}
Summary:        PDL::Slatec Perl module
License:        CHECK(Distributable)
URL:            https://metacpan.org/dist/PDL-Slatec
Source0:        http://www.cpan.org/authors/id/E/ET/ETJ/PDL-Slatec-%{version}.tar.gz
BuildRequires:  make
BuildRequires:  gcc-gfortran
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(:VERSION) >= 5.16.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::F77)
BuildRequires:  perl(PDL) >= 2.094
BuildRequires:  perl(Test::Exception)
Requires:       perl(PDL) >= 2.094

%description
PDL::Slatec Perl module

%prep
%setup -q -n PDL-Slatec-%{version}

%build
#perl Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS" NO_PACKLIST=1 NO_PERLLOCAL=1
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%files
%doc Changes slatec.pd
%license 
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/PDL*
%{_mandir}/man3/*

%changelog
* Tue Jan 20 2026 Stuart Campbell (scampbell@bnl.gov) - 2.097-2
- Removed OPTIMIZE flag

* Sun Jan 18 2026 Stuart Campbell (scampbell@bnl.gov) 2.097-1
- Specfile autogenerated by cpanspec 1.78.
